name: Build EXE (Windows)

on:
  push:
    tags:
      - 'v*'   # 태그 push될 때 실행

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build client exe (4G)
        run: >
          pyinstaller --onedir cli/main.py
          --add-data "bin;resources/bin"
          --add-data "proto;resources/proto"
          --add-data "cli/data;../data"
          --name nocli-client-4g
      
      - name: Build client exe (5G)
        run: >
          pyinstaller --onedir cli/main.py
          --add-data "bin;resources/bin"
          --add-data "proto;resources/proto"
          --add-data "cli/data;../data"
          --name nocli-client-5g
        

      - name: Zip 4G build
        run: powershell Compress-Archive -Path dist/nocli-client-4g -DestinationPath nocli-client-4g.zip

      - name: Zip 5G build
        run: powershell Compress-Archive -Path dist/nocli-client-5g -DestinationPath nocli-client-5g.zip

      - name: Upload 4G artifact
        uses: actions/upload-artifact@v4
        with:
          name: nocli-client-4g_${{ github.ref_name }}
          path: nocli-client-4g.zip

      - name: Upload 5G artifact
        uses: actions/upload-artifact@v4
        with:
          name: nocli-client-5g_${{ github.ref_name }}
          path: nocli-client-5g.zip
