name: Build EXE (Windows)

on:
  workflow_dispatch:   # GitHub에서 수동으로 실행할 수 있게 함

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build client exe
        run: pyinstaller --onefile cli/main.py --name nocli-client

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-exe
          path: dist/*.exe

